### ISSUE TITLE
[JOSS] Poetry installation failure

### ISSUE THREAD

**Issue by edeno** [mlfpm/deepof#10]
I also tried installing via poetry and received the following error:
```bash
poetry install

Poetry could not find a pyproject.toml file in /home/edeno/Documents/Github/deepof or its parents
```

xref: https://github.com/openjournals/joss-reviews/issues/5394

**Comment by lucasmiranda42** [comment]
Dear @edeno, first of all thank you so much for reviewing DeepOF!

I start with this one because it seems like the easiest to troubleshoot. Sorry to ask, but are you in the correct directory? is pyproject.toml in the directory from which you're calling `poetry install`?

I realize the documentation may be a bit ambiguous here; let me know if you manage and I'll edit the text to make it clearer

**Comment by edeno** [comment]
Ah I actually discovered the problem. I didn't have git-lfs installed, which I think caused an error in cloning. If you could include this in your documentation that would be great.

Another small issue discovered. Python <3.11 is required.

**Comment by lucasmiranda42** [comment]
Wonderful, glad you managed! I'll add the Python version to the documentation.

**Comment by lucasmiranda42** [comment]
Dear @edeno, I removed the git lfs requirement from the repo and updated the documentation to specify the Python version. I'll close the issue for now; let me know if you would like me to implement any further changes :)
